# 需要配置 referer
[list_headers]
accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
priority = "u=0, i"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "document"
sec-fetch-mode = "navigate"
sec-fetch-site = "none"
sec-fetch-user = "?1"
upgrade-insecure-requests = "1"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"

# 需要配置 referer
[body_headers]
accept = "application/json, text/plain, */*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
client-version = "v2.47.25"
priority = "u=1, i"
referer = "https://weibo.com/1644114654/OiZre8dir?refer_flag=1001030103_"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
server-version = "v2025.01.23.1"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-requested-with = "XMLHttpRequest"
x-xsrf-token = "seBDSEeh70cZTEWGWWkFmxxG"


# 需要配置 referer x-xsrf-token
[comment1_buildComments_headers]
accept = "application/json, text/plain, */*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
client-version = "v2.47.25"
priority = "u=1, i"
referer = "https://weibo.com/1644114654/OiZre8dir"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
server-version = "v2025.01.23.1"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-requested-with = "XMLHttpRequest"
x-xsrf-token = "seBDSEeh70cZTEWGWWkFmxxG"

# 需要配置 referer
[comment2_buildComments_headers]
accept = "application/json, text/plain, */*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
client-version = "v2.47.25"
priority = "u=1, i"
referer = "https://weibo.com/1644114654/OiZre8dir"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
server-version = "v2025.01.23.1"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-requested-with = "XMLHttpRequest"
x-xsrf-token = "seBDSEeh70cZTEWGWWkFmxxG"


# 需要配置 referer  x-xsrf-token
[comment1_rum_headers]
accept = "*/*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
content-type = "multipart/form-data; boundary=----WebKitFormBoundaryP8RPAfGDm1mdduKE"
origin = "https://weibo.com"
priority = "u=1, i"
referer = "https://weibo.com/1644114654/OiZre8dir"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-xsrf-token = "seBDSEeh70cZTEWGWWkFmxxG"


# 需要配置 referer  x-xsrf-token
[comment2_rum_headers]
accept = "*/*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
content-type = "multipart/form-data; boundary=----WebKitFormBoundary0CRQdyFBn3rj8Xh2"
origin = "https://weibo.com"
priority = "u=1, i"
referer = "https://weibo.com/1644114654/OiZre8dir"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-xsrf-token = "seBDSEeh70cZTEWGWWkFmxxG"


# 需要配置 referer  x-xsrf-token
[login_signin_headers]
accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
cache-control = "max-age=0"
priority = "u=0, i"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "document"
sec-fetch-mode = "navigate"
sec-fetch-site = "same-origin"
sec-fetch-user = "?1"
upgrade-insecure-requests = "1"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"


# 需要配置 referer  x-xsrf-token
[login_qrcode_headers]
accept = "application/json, text/plain, */*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
priority = "u=1, i"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-requested-with = "XMLHttpRequest"


# 需要配置 referer  x-xsrf-token
[login_final_headers]
accept = "application/json, text/plain, */*"
accept-language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
priority = "u=1, i"
sec-ch-ua = "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\""
sec-ch-ua-mobile = "?0"
sec-ch-ua-platform = "\"Windows\""
sec-fetch-dest = "empty"
sec-fetch-mode = "cors"
sec-fetch-site = "same-origin"
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"
x-requested-with = "XMLHttpRequest"


[cookies]
SCF = "AnQhEA08TUG9ln2r7R0-cHMvj3KTSZb-85kfIcXTHqooYhjTcn-UkaGS5792LpSqqbJApBlXrIheowZ1k4aYR1Q."
SUB = "_2A25Kkj8dDeRhGeFJ4lIT9CzNyj6IHXVp7j7VrDV8PUNbmtAYLVT5kW9NfsmQ4UzJuUOhUQbYBkUvv3HADVVzl9Ig"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9W5Oj.LmOvr7_7fS8d6lYxiZ5JpX5KzhUgL.FoMN1K5EShzpeKz2dJLoIp7LxKML1KBLBKnLxKqL1hnLBoMNS0.7eoBEeK2E"
ALF = "02_1740495949"
SINAGLOBAL = "970667482772.5692.1737903974414"
_s_tentry = "-"
Apache = "6816769468273.411.1738037552250"
ULV = "1738037552254:3:3:3:6816769468273.411.1738037552250:1737957449024"
XSRF-TOKEN = "11rI6hKDuc3K5G2ezF4z0hBS"
PC_TOKEN = "5244ffa483"
WBPSESS = "2bPq4LTfaY-EnTnt8h5hWX9KGoz50scMNqd4lpDCT8IiCLnpv2C9Z_Kk8JVbYkIyBQ0eFNYccRFpnV_A6ntYby9mRTSp4yVHVscMtbb6neav_FRsiuVo3dDFXhgFIDTEunS8nK_U_4EmshtOSYLo3w=="


[update_info]
update_time = "2025/02/01 00:00:00"