[database]
path = "../数据库.db"

[cookies]
SCF = ""
SUB = ""
SUBP = ""
ALF = ""
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = ""
X-CSRF-TOKEN = ""

[cookies_info]
update_time = "2025-02-20 20:02:45"
